### PR TITLE
Fix capture mode respawn time (fix #64)

### LINKED ISSUE #64: Fix capture mode respawn time
I totally support the change of the respawn time in capture to 10 seconds instead of the current 5s for the named reasons:

http://cubeengine.com/forum.php?action=display_thread&thread_id=2666http://cubeengine.com/forum.php?action=display_thread&thread_id=2666

What do you all think about that?

### PR DESCRIPTION
**Pull request by Croydon**
Credits to @super-tux 

This was done at the Hackathon 2017 but kinda got lost...

### CODE REVIEW

**Comment by Fohlen** [comment]
+1 for bringing it back then

**Comment by Croydon** [comment]
Could someone please finally review this?

File: inexor/client/gamemode/capture_client.hpp [hunk 1]
```diff
@@ -38,8 +38,8 @@ struct captureclientmode : clientmode, capturemode_common
 
     int respawnwait(fpsent *d) override
     {
-        if(m_regencapture) return -1;
-        return max(0, RESPAWNSECS-(lastmillis-d->lastpain)/1000);
+        // if(m_regencapture) return -1;
```
Comment (a-teammate) [inline inexor/client/gamemode/capture_client.hpp]: can't test currently, but I wouldn't comment this line but remove it
